### ISSUE TITLE
where can i find the dataset?

### ISSUE THREAD

**Issue by WCH-Steven** [Shashant-R/GSCEventMOD#3]
I am a graduate student of Fudan University. I have been doing some work on event-based cameras recently. I hope to reproduce and try to improve this paper. Is there any way to obtain the data set in the paper?

**Comment by Shashant-R** [comment]
Do have a look at our paper at https://ieeexplore.ieee.org/abstract/document/9607843. In the you can notice that the datasets for working on the paper was developed by Mohammad Almatrafi on his paper on Distance Surface for Event-Based Optical Flow. You can find the DVSMOTION20 dataset here at https://sites.google.com/a/udayton.edu/issl/software/dataset. Hope this helps.

**Comment by WCH-Steven** [comment]
> Do have a look at our paper at https://ieeexplore.ieee.org/abstract/document/9607843. In the you can notice that the datasets for working on the paper was developed by Mohammad Almatrafi on his paper on Distance Surface for Event-Based Optical Flow. You can find the DVSMOTION20 dataset here at https://sites.google.com/a/udayton.edu/issl/software/dataset. Hope this helps.

thx very much
